name: Deployment
on:
  push:
    branches: [main, dev]

env:
  NODE_VERSION: "22.16.0"
  PNPM_VERSION: "10.8.1"

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: 🥁 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔍 Run lint
        run: pnpm lint

  typecheck:
    name: 🔍 Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: 🥁 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔍 Run type check
        run: pnpm typecheck

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: 🥁 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔍 Run tests
        run: pnpm test
